// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: movie/movie.proto

package movie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMovieResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *GetMovieResultRequest) Reset() {
	*x = GetMovieResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResultRequest) ProtoMessage() {}

func (x *GetMovieResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResultRequest.ProtoReflect.Descriptor instead.
func (*GetMovieResultRequest) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{0}
}

func (x *GetMovieResultRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetMovieResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title         string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Actors        []string `protobuf:"bytes,2,rep,name=actors,proto3" json:"actors,omitempty"`
	Directors     []string `protobuf:"bytes,3,rep,name=directors,proto3" json:"directors,omitempty"`
	Genre         []string `protobuf:"bytes,4,rep,name=genre,proto3" json:"genre,omitempty"`
	YearOfRelease string   `protobuf:"bytes,5,opt,name=year_of_release,json=yearOfRelease,proto3" json:"year_of_release,omitempty"`
	Language      []string `protobuf:"bytes,6,rep,name=language,proto3" json:"language,omitempty"`
}

func (x *GetMovieResultResponse) Reset() {
	*x = GetMovieResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResultResponse) ProtoMessage() {}

func (x *GetMovieResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResultResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResultResponse) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{1}
}

func (x *GetMovieResultResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetMovieResultResponse) GetActors() []string {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *GetMovieResultResponse) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *GetMovieResultResponse) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *GetMovieResultResponse) GetYearOfRelease() string {
	if x != nil {
		return x.YearOfRelease
	}
	return ""
}

func (x *GetMovieResultResponse) GetLanguage() []string {
	if x != nil {
		return x.Language
	}
	return nil
}

var File_movie_movie_proto protoreflect.FileDescriptor

var file_movie_movie_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2d, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0xbe, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x79, 0x65, 0x61, 0x72, 0x5f, 0x6f, 0x66,
	0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x79, 0x65, 0x61, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x32, 0x5b, 0x0a, 0x0c, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_movie_movie_proto_rawDescOnce sync.Once
	file_movie_movie_proto_rawDescData = file_movie_movie_proto_rawDesc
)

func file_movie_movie_proto_rawDescGZIP() []byte {
	file_movie_movie_proto_rawDescOnce.Do(func() {
		file_movie_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_movie_movie_proto_rawDescData)
	})
	return file_movie_movie_proto_rawDescData
}

var file_movie_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_movie_movie_proto_goTypes = []any{
	(*GetMovieResultRequest)(nil),  // 0: grpc.GetMovieResultRequest
	(*GetMovieResultResponse)(nil), // 1: grpc.GetMovieResultResponse
}
var file_movie_movie_proto_depIdxs = []int32{
	0, // 0: grpc.MovieService.GetMovieInfo:input_type -> grpc.GetMovieResultRequest
	1, // 1: grpc.MovieService.GetMovieInfo:output_type -> grpc.GetMovieResultResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movie_movie_proto_init() }
func file_movie_movie_proto_init() {
	if File_movie_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_movie_movie_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetMovieResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_movie_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetMovieResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_movie_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_movie_proto_goTypes,
		DependencyIndexes: file_movie_movie_proto_depIdxs,
		MessageInfos:      file_movie_movie_proto_msgTypes,
	}.Build()
	File_movie_movie_proto = out.File
	file_movie_movie_proto_rawDesc = nil
	file_movie_movie_proto_goTypes = nil
	file_movie_movie_proto_depIdxs = nil
}
